# database generated on 2025-01-22 06:27 GMT
!!omap
- /home/lhh/test_riscvof/riscv-arch-test/riscv-test-suite/rv32i_m/M/src/div-01.S:
    commit_id: 9b503d7890296e53aa8a06e49ebef3c61ce5d3fd
    isa:
    - RV32IM
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*M.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - div
- /home/lhh/test_riscvof/riscv-arch-test/riscv-test-suite/rv32i_m/M/src/divu-01.S:
    commit_id: 3c7e9d41d4efb9dcb9c0af83e0eecbe28327bf3c
    isa:
    - RV32IM
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*M.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - divu
- /home/lhh/test_riscvof/riscv-arch-test/riscv-test-suite/rv32i_m/M/src/mul-01.S:
    commit_id: 3c7e9d41d4efb9dcb9c0af83e0eecbe28327bf3c
    isa:
    - RV32IM
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*M.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - mul
- /home/lhh/test_riscvof/riscv-arch-test/riscv-test-suite/rv32i_m/M/src/mulh-01.S:
    commit_id: 3c7e9d41d4efb9dcb9c0af83e0eecbe28327bf3c
    isa:
    - RV32IM
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*M.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - mulh
- /home/lhh/test_riscvof/riscv-arch-test/riscv-test-suite/rv32i_m/M/src/mulhsu-01.S:
    commit_id: a02feaee118fbea01fbb8fdcdf62bce6f7067478
    isa:
    - RV32IM
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*M.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - mulhsu
- /home/lhh/test_riscvof/riscv-arch-test/riscv-test-suite/rv32i_m/M/src/mulhu-01.S:
    commit_id: 3c7e9d41d4efb9dcb9c0af83e0eecbe28327bf3c
    isa:
    - RV32IM
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*M.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - mulhu
- /home/lhh/test_riscvof/riscv-arch-test/riscv-test-suite/rv32i_m/M/src/rem-01.S:
    commit_id: 3c7e9d41d4efb9dcb9c0af83e0eecbe28327bf3c
    isa:
    - RV32IM
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*M.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - rem
- /home/lhh/test_riscvof/riscv-arch-test/riscv-test-suite/rv32i_m/M/src/remu-01.S:
    commit_id: 3c7e9d41d4efb9dcb9c0af83e0eecbe28327bf3c
    isa:
    - RV32IM
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*M.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - remu
